const productData = [
    { id: 1, name: "Pakistan GUL E LALA", desc: "A classic and beloved fragrance, especially for elders.", gender: "Male", prices: { "7ml": 90, "30ml": { regular: 400, offer: 310 }, "100ml": { regular: 900, offer: 730 } }, longevity: "১২-১৮ ঘণ্টা", scentType: "ক্লাসিক ও ঐতিহ্যবাহী", notes: { top: "গোলাপ, জাফরান", middle: "عود, জেসমিন", base: "আম্বার, কস্তুরী" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=GUL+1", "https://placehold.co/600x600/023020/F5F5F5?text=GUL+2", "https://placehold.co/600x600/023020/F5F5F5?text=GUL+3"] },
    { id: 2, name: "SRK", desc: "A very popular perfume scent.", gender: "Male", prices: { "7ml": 90, "30ml": { regular: 450, offer: 350 }, "100ml": { regular: 1050, offer: 850 } }, longevity: "১০-১২ ঘণ্টা", scentType: "শক্তিশালী ও আকর্ষণীয়", notes: { top: "লেবু, বারগামট", middle: "ল্যাভেন্ডার, মশলা", base: "চন্দন, ভেটিভার" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=SRK+1", "https://placehold.co/600x600/023020/F5F5F5?text=SRK+2", "https://placehold.co/600x600/023020/F5F5F5?text=SRK+3"] },
    { id: 3, name: "BLU DE CHANELS", desc: "A very popular and well-known perfume.", gender: "Male", prices: { "7ml": 90, "30ml": { regular: 460, offer: 370 }, "100ml": { regular: 1100, offer: 899 } }, longevity: "৮-১০ ঘণ্টা", scentType: "ফ্রেশ ও আধুনিক", notes: { top: "সাইট্রাস, মিন্ট", middle: "আদা, জেসমিন", base: "সিডারউড, প্যাচুলি" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=BLU+1", "https://placehold.co/600x600/023020/F5F5F5?text=BLU+2", "https://placehold.co/600x600/023020/F5F5F5?text=BLU+3"] },
    { id: 4, name: "Green Apple", desc: "An attractive apple-type scent.", gender: "Unisex", prices: { "7ml": 90, "30ml": { regular: 400, offer: 320 }, "100ml": { regular: 950, offer: 760 } }, longevity: "৬-৮ ঘণ্টা", scentType: "মিষ্টি ও ফলভিত্তিক", notes: { top: "সবুজ আপেল", middle: "ফ্রুট নোটস", base: "কস্তুরী" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Apple+1", "https://placehold.co/600x600/023020/F5F5F5?text=Apple+2", "https://placehold.co/600x600/023020/F5F5F5?text=Apple+3"] },
    { id: 5, name: "Smoking", desc: "A floral and lavender fragrance.", gender: "Male", prices: { "7ml": 90, "30ml": { regular: 450, offer: 350 }, "100ml": { regular: 1050, offer: 850 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
    { id: 6, name: "BLUE LADY", desc: "A very common perfume for women.", gender: "Female", prices: { "7ml": 90, "30ml": { regular: 400, offer: 320 }, "100ml": { regular: 940, offer: 750 } }, longevity: "৮-১২ ঘণ্টা", scentType: "ফ্লোরাল ও মিষ্টি", notes: { top: "টিউবাররোজ, জেসমিন", middle: "ফ্রুট নোটস", base: "ভ্যানিলা, স্যান্ডালউড" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=LADY+1", "https://placehold.co/600x600/023020/F5F5F5?text=LADY+2", "https://placehold.co/600x600/023020/F5F5F5?text=LADY+3"] },
    { id: 7, name: "ONE MILLION", desc: "A very common international perfume.", gender: "Unisex", prices: { "7ml": 90, "30ml": { regular: 500, offer: 400 }, "100ml": { regular: 1250, offer: 1000 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
    { id: 8, name: "SHAY OUD", desc: "A very common Oud-type scent.", gender: "Male", prices: { "7ml": 90, "30ml": { regular: 460, offer: 370 }, "100ml": { regular: 1150, offer: 920 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
    { id: 9, name: "MAGNET", desc: "A common sweet (strong) perfume.", gender: "Unisex", prices: { "7ml": 90, "30ml": { regular: 400, offer: 310 }, "100ml": { regular: 900, offer: 730 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
    { id: 10, name: "MOON DROPS", desc: "A very attractive perfume for women.", gender: "Female", prices: { "7ml": 90, "30ml": { regular: 400, offer: 320 }, "100ml": { regular: 940, offer: 750 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
    { id: 11, name: "ACQUA DI GIO", desc: "A very common perfume for men.", gender: "Male", prices: { "7ml": 90, "30ml": { regular: 560, offer: 450 }, "100ml": { regular: 1500, offer: 1200 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
    { id: 12, name: "ARMANY", desc: "A very common perfume for men.", gender: "Male", prices: { "7ml": 90, "30ml": { regular: 450, offer: 350 }, "100ml": { regular: 1050, offer: 850 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
    { id: 13, name: "FROOTI (Perfume Grade)", desc: "A very attractive sweet fruit scent.", gender: "Unisex", prices: { "7ml": 90, "30ml": { regular: 620, offer: 500 }, "100ml": { regular: 1600, offer: 1300 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
    { id: 14, name: "DE LEMON", desc: "An attractive lemon scent.", gender: "Unisex", prices: { "7ml": 90, "30ml": { regular: 380, offer: 300 }, "100ml": { regular: 860, offer: 690 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
    { id: 15, name: "DE ORANGE", desc: "An attractive orange scent.", gender: "Unisex", prices: { "7ml": 90, "30ml": { regular: 360, offer: 290 }, "100ml": { regular: 850, offer: 680 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
    { id: 16, name: "X CHILL BLUE", desc: "A very attractive perfume scent.", gender: "Male", prices: { "7ml": 90, "30ml": { regular: 420, offer: 340 }, "100ml": { regular: 1000, offer: 799 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
    { id: 17, name: "GOOD GIRL 3.4", desc: "A very common perfume for women.", gender: "Female", prices: { "7ml": 90, "30ml": { regular: 480, offer: 380 }, "100ml": { regular: 1200, offer: 950 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
    { id: 18, name: "WATER MELON", desc: "A watermelon or Center Shock chewing gum flavor.", gender: "Unisex", prices: { "7ml": 90, "30ml": { regular: 500, offer: 399 }, "100ml": { regular: 1250, offer: 1000 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
    { id: 19, name: "MIX BERRY", desc: "A berry fruit flavor.", gender: "Unisex", prices: { "7ml": 90, "30ml": { regular: 380, offer: 300 }, "100ml": { regular: 870, offer: 699 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
    { id: 20, name: "CANDY", desc: "A vanilla and chocolate type scent.", gender: "Unisex", prices: { "7ml": 90, "30ml": { regular: 560, offer: 450 }, "100ml": { regular: 1420, offer: 1140 } }, longevity: "৮-১২ ঘণ্টা", scentType: "কড়া টাইপের ফ্লেভার", notes: { top: "ডিফল্ট", middle: "ডিফল্ট", base: "ডিফল্ট" }, images: ["https://placehold.co/600x600/023020/F5F5F5?text=Perfume+1", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+2", "https://placehold.co/600x600/023020/F5F5F5?text=Perfume+3"] },
];

const langData = {
    en: {
        title: "Sylflora | Luxury Perfume Shop",
        nav_shop: "Shop",
        nav_test_kit: "Test Kit",
        nav_about: "About",
        nav_contact: "Contact",
        nav_shop_mobile: "Shop",
        nav_test_kit_mobile: "Test Kit",
        nav_about_mobile: "About",
        nav_contact_mobile: "Contact",
        hero_subtitle: "Luxury Perfume Shop",
        kit_title: "Create Your Own 7ml Test Kit",
        kit_subtitle: "Select a minimum of 5 perfumes to create your personalized 7ml sample kit.",
        kit_button: "Create Your Kit",
        kit_search_placeholder: "Search for a perfume to add...",
        kit_selection_counter: "Select at least 5 perfumes",
        kit_add_to_cart: "Add Kit to Cart",
        shop_title: "Our Collection",
        shop_subtitle: "Discover your signature scent from our curated collection.",
        search_placeholder: "Search for perfumes...",
        filter_all: "All",
        filter_men: "For Men",
        filter_women: "For Women",
        filter_unisex: "Unisex",
        sort_default: "Sort By",
        sort_price_asc: "Price: Low to High",
        sort_price_desc: "Price: High to Low",
        about_title: "The Essence of Sylflora",
        about_intro: "Explore the story behind our fragrances and see a visual breakdown of our perfume offerings.",
        about_p1: "Welcome to Sylflora, where the art of perfumery meets the essence of nature and luxury. Our mission is to create unique, high-quality fragrances that tell a story and evoke powerful emotions.",
        about_p2: "We believe that a scent is more than just a fragrance; it's a personal signature. That's why we source the finest ingredients from around the world to create our exclusive collection.",
        chart_title: "Our Collection by Category",
        contact_title: "Get In Touch",
        contact_subtitle: "For inquiries, support, or feedback, please reach out.",
        form_name_placeholder: "Name",
        form_message_placeholder: "Your Message",
        contact_facebook: "Message us on Facebook",
        modal_size_title: "Select Size",
        modal_add_to_cart: "Add to Cart",
        instant_buy: "Instant Buy",
        modal_longevity: "Longevity",
        modal_scent_type: "Scent Type",
        modal_fragrance_notes: "Fragrance Notes",
        modal_notes_top: "Top",
        modal_notes_middle: "Middle",
        modal_notes_base: "Base",
        gender_male: "For Men",
        gender_female: "For Women",
        gender_unisex: "Unisex",
        price_tba: "Price TBA",
        add_success_title: "Successfully Added!",
        add_success_message: "'%productName%' has been added to your cart!",
        continue_shopping: "Continue Shopping",
        go_to_cart: "Go to Cart",
        cart_title: "Shopping Cart",
        cart_subtotal: "Subtotal",
        cart_checkout: "Checkout",
        cart_clear: "Clear Cart",
        cart_empty: "Your cart is empty.",
        checkout_title: "Confirm Order",
        checkout_summary_title: "Order Summary",
        checkout_details_title: "Your Details",
        checkout_form_name: "Your Name",
        checkout_form_phone: "Your Mobile Number* (11 Digits)",
        checkout_form_address: "Your Full Address\n(Thana, District, and where will the delivery person come?*)",
        checkout_delivery_location: "Delivery Location",
        
        checkout_inside_dhaka: 'Inside Dhaka<br><span style="font-size: 0.8em;">(80 tk)</span>',
checkout_outside_dhaka: 'Outside Dhaka<br><span style="font-size: 0.8em;">(130 tk)</span>',

        checkout_payment_method: "Payment Method",
        checkout_cod: "Cash on Delivery",
        checkout_delivery_time: "✅Pay after receiving the product. <br>🚚Delivery Time: 1-3 days in Dhaka, <br> 3-5 days outside Dhaka.",

        checkout_confirm_order: "Confirm Order (COD)",
        checkout_facebook_help: 'For any help, message us on,<br><a href="https://www.facebook.com/sylflora.official" target="_blank" class="text-blue-600 font-bold hover:underline">our Facebook Page</a>.',
        order_placed_title: "Your order has been received successfully!",
        order_placed_p1: "To confirm the order, one of our representatives may call you.",
        order_placed_p2: "Calls are made 6 days a week, except Friday, between 10 AM and 7 PM.",
        order_placed_p3: 'For any assistance, message us on our <a href="https://www.facebook.com/sylflora.official" target="_blank" class="font-bold text-blue-600 hover:underline">Facebook Page</a>.',
        order_placed_button: "Got It"
    },
    bn: {
        title: "সিলফ্লোরা | লাক্সারি পারফিউম শপ",
        nav_shop: "শপ",
        nav_test_kit: "টেস্ট কিট",
        nav_about: "আমাদের সম্পর্কে",
        nav_contact: "যোগাযোগ",
        nav_shop_mobile: "শপ",
        nav_test_kit_mobile: "টেস্ট কিট",
        nav_about_mobile: "আমাদের সম্পর্কে",
        nav_contact_mobile: "যোগাযোগ",
        hero_subtitle: "লাক্সারি পারফিউম শপ",
        kit_title: "আপনার নিজের ৭মিলি টেস্ট কিট তৈরি করুন",
        kit_subtitle: "পুরো বোতল কেনার সিদ্ধান্ত নিতে পারছেন না? আপনার ব্যক্তিগত ৭মিলি নমুনার কিট তৈরি করতে আমাদের সংগ্রহ থেকে সর্বনিম্ন ৫টি পারফিউম নির্বাচন করুন।",
        kit_button: "আপনার কিট তৈরি করুন",
        kit_search_placeholder: "কিটে যোগ করতে পারফিউম খুঁজুন...",
        kit_selection_counter: "কমপক্ষে ৫টি পারফিউম নির্বাচন করুন",
        kit_add_to_cart: "কিট কার্টে যোগ করুন",
        shop_title: "আমাদের সংগ্রহ",
        shop_subtitle: "আমাদের বিলাসবহুল পারফিউমের সংগ্রহ থেকে আপনার পছন্দের সুগন্ধি আবিষ্কার করুন।",
        search_placeholder: "পারফিউম খুঁজুন...",
        filter_all: "সব",
        filter_men: "পুরুষদের জন্য",
        filter_women: "মহিলাদের জন্য",
        filter_unisex: "ইউনিসেক্স",
        sort_default: "সাজান",
        sort_price_asc: "মূল্য: কম থেকে বেশি",
        sort_price_desc: "মূল্য: বেশি থেকে কম",
        about_title: "সিলফ্লোরার সারমর্ম",
        about_intro: "আমাদের সুগন্ধির পেছনের গল্পটি অন্বেষণ করুন এবং আমাদের পারফিউম অফারগুলির একটি ভিজ্যুয়াল ব্রেকডাউন দেখুন।",
        about_p1: "সিলফ্লোরাতে স্বাগতম, যেখানে পারফিউমারির শিল্প প্রকৃতি এবং বিলাসিতার সারাংশের সাথে মিলিত হয়। আমাদের লক্ষ্য হল অনন্য, উচ্চ-মানের সুগন্ধি তৈরি করা যা একটি গল্প বলে এবং শক্তিশালী আবেগ জাগিয়ে তোলে।",
        about_p2: "আমরা বিশ্বাস করি যে একটি ঘ্রাণ কেবল একটি সুগন্ধির চেয়ে বেশি কিছু; এটি একটি ব্যক্তিগত স্বাক্ষর। এজন্যই আমরা আমাদের একচেটিয়া সংগ্রহ তৈরি করতে বিশ্বজুড়ে সেরা উপাদানগুলি সংগ্রহ করি।",
        chart_title: "বিভাগ অনুসারে আমাদের সংগ্রহ",
        contact_title: "যোগাযোগ করুন",
        contact_subtitle: "জিজ্ঞাসা, সমর্থন বা মতামতের জন্য, দয়া করে যোগাযোগ করুন।",
        form_name_placeholder: "আপনার নাম",
        form_message_placeholder: "আপনার বার্তা",
        contact_facebook: "ফেসবুকে মেসেজ দিন",
        modal_size_title: "সাইজ বাছাই করুন",
        modal_add_to_cart: "কার্টে যোগ করুন",
        instant_buy: "এখনই কিনুন",
        modal_longevity: "স্থায়িত্ব",
        modal_scent_type: "ধরণ",
        modal_fragrance_notes: "সুগন্ধি নোট",
        modal_notes_top: "শীর্ষ",
        modal_notes_middle: "মধ্য",
        modal_notes_base: "বেস",
        gender_male: "পুরুষদের জন্য",
        gender_female: "মহিলাদের জন্য",
        gender_unisex: "ইউনিসেক্স",
        price_tba: "মূল্য TBA",
        add_success_title: "সফলভাবে যোগ হয়েছে!",
        add_success_message: "'%productName%' আপনার শপিং কার্টে যোগ করা হয়েছে!",
        continue_shopping: "শপিং চালিয়ে যান",
        go_to_cart: "কার্টে যান",
        cart_title: "শপিং কার্ট",
        cart_subtotal: "মোট",
        cart_checkout: "চেকআউট",
        cart_clear: "কার্ট খালি করুন",
        cart_empty: "আপনার কার্ট খালি।",
        checkout_title: "অর্ডার কনফার্ম করুন",
        checkout_summary_title: "অর্ডার সারাংশ",
        checkout_details_title: "আপনার তথ্য",
        checkout_form_name: "আপনার নাম",
        checkout_form_phone: "আপনার মোবাইল নাম্বার* (১১ ডিজিট)",
        checkout_form_address: "আপনার সম্পূর্ণ ঠিকানা\n(থানা, জেলা এবং ডেলিভারী ম্যান কোথায় আসবে?*)",
        checkout_delivery_location: "ডেলিভারি এলাকা",
        checkout_inside_dhaka: 'ঢাকার মধ্যে <br> <span style="font-size: 0.8em;">(৮০ টাকা)</span>',
        
        checkout_outside_dhaka: 'ঢাকার বাইরে <br> <span style="font-size: 0.8em;">(১৩০ টাকা)</span>',

        checkout_payment_method: "পেমেন্ট পদ্ধতি",
        checkout_cod: "ক্যাশ অন ডেলিভারি",
        
        checkout_delivery_time: `✅পণ্য হাতে পেয়ে মূল্য পরিশোধ করুন। <br> 
<span style="font-size:0.75em;">ডেলিভারি সময়: ঢাকা শহরে ১-৩ দিন, ঢাকার বাইরে ৩-৫ দিন।</span>`,

        checkout_confirm_order: "অর্ডার কনফার্ম করুন (COD)",
        checkout_facebook_help: 'যেকোনো সাহায্যের জন্য মেসেজ করুন,<br>আমাদের <a href="https://www.facebook.com/sylflora.official" target="_blank" class="text-blue-600 font-bold hover:underline">Facebook পেজে</a>।',
        order_placed_title: "আপনার অর্ডারটি সফলভাবে গৃহীত হয়েছে!",
        order_placed_p1: "অর্ডারটি কনফার্ম করার জন্য আমাদের একজন প্রতিনিধি আপনাকে কল করতে পারেন।",
        order_placed_p2: "শুক্রবার ব্যতীত সপ্তাহে ৬ দিন সকাল ১০ টা থেকে সন্ধ্যা ৭ টার মধ্যে কল করা হয়।",
        order_placed_p3: 'যেকোনো প্রয়োজনে মেসেজ করুন আমাদের <a href="https://www.facebook.com/sylflora.official" target="_blank" class="font-bold text-blue-600 hover:underline">Facebook পেজে</a>।',
        order_placed_button: "ঠিক আছে"
    }
};
